language: java
jdk:
- oraclejdk8
script: mvn -V -e -B clean verify
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -e -B site-deploy
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
  - $HOME/.m2/repository
before_cache:
- rm -rf $HOME/.m2/repository/com/github/jonasrutishauser
