name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/common-ci.yml
    with:
      codeql: false # contains no code
      deploy-site: ${{ github.event_name == 'push' }}
      publish-test-report: false
      publish-coverage-report: false
      sonar-report: false
