name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 1.8
          - 11
          - 17
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ matrix.java }} ${{ runner.os }}-m2
      - name: Setup Git
        run: >
          git config --global user.email "actions@github.com" && 
          git config --global user.name "GitHub Actions"
        if: ${{ !startsWith(github.event_name, 'pull_request') }}
      - name: Build with Maven
        run: mvn -B -V -e verify
      - name: Deploy Site
        if: ${{ matrix.java == '1.8' && github.event_name != 'release' && !startsWith(github.event_name, 'pull_request') }}
        run: mvn -B -e site-deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
