name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 1.8
          - 11
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/maven-ci
        with:
          java-version: ${{ matrix.java }}
          coverage: false
          sonar: false
          site: ${{ matrix.java == '1.8' }}

